language: clojure
lein: lein2
script: lein2 cljsbuild test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
 - sudo add-apt-repository ppa:chris-lea/node.js -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq phantomjs nodejs