language: clojure
lein: lein2
script: lein2 with-profile test cljsbuild test slimerjs-test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "34.0"
before_script:
  - "echo 'Installing Slimer'"
  - "wget http://download.slimerjs.org/releases/0.9.5/slimerjs-0.9.5.zip"
  - "unzip slimerjs-0.9.5.zip"
  - "mv slimerjs-0.9.5 ./slimerjs"